### ISSUE TITLE
Gobbledygook

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#101]
I pushed the new WP update for OCS and now I have these lines showing everywhere... front and back ends. 

![image](https://cloud.githubusercontent.com/assets/6453589/17823368/fc386598-6610-11e6-9acd-617f9f179ec9.png)

![image](https://cloud.githubusercontent.com/assets/6453589/17823385/0bec2010-6611-11e6-8d0d-643cd327c2ad.png)

**Comment by alisonjbates** [comment]
Most likely this is an error generated because the WP core has been updated. The new version requires a database update, and most likely the web host is using an out of date version of MySQL.

The two most common fixes are to contact the host for an update/upgrade, or to add the "DB_COLLATE” declaration to the wp-config.php. I can do the latter, but it would be faster to test if it was done in house.

https://codex.wordpress.org/Editing_wp-config.php#Database_character_set <https://codex.wordpress.org/Editing_wp-config.php#Database_character_set>


You can look here to see the tech the current site/ host is using:
http://oregonconservationstrategy.org/wordpress/wp-admin/options-general.php?page=updraftplus&tab=status

And here are the WP 4.6 requirements:
https://wordpress.org/about/requirements/ <https://wordpress.org/about/requirements/>

Hope this helps!
alison

**Comment by alisonjbates** [comment]
We may need both DB_CHARSET and DB_COLLATE, but be sure to read the information regarding the two from the codex.

The other option is to just turn off the error reporting… I don’t believe this error generally causes problems with functionality… Though this is not what I am recommending!
