### ISSUE TITLE
Compass Map View(s)

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#20]
Placeholder ticket mostly. Full functionality TBD.

Many pages will have a single 'master'  compass map (url entered via custom field, displayed via iframe). That map will be hidden by default and displayed when the map icon in the top bar is clicked.

<img width="320" alt="Map Icon" src="https://cloud.githubusercontent.com/assets/54206/9713041/be9d609a-5503-11e5-83f2-c643455fc3df.png">

Map iframe should fill the entire content area.
<img width="461" alt="screen shot 2015-09-07 at 2 22 10 am" src="https://cloud.githubusercontent.com/assets/54206/9713588/48c91d6a-5507-11e5-9469-cda2d58e098f.png">
<img width="434" alt="screen shot 2015-09-07 at 2 23 16 am" src="https://cloud.githubusercontent.com/assets/54206/9713620/777d1e0e-5507-11e5-95b7-6374d731930c.png">

Other Compass map links will be inline within the content (via shortcode). Whether or not these will be displayed inline or via some sort of 'Show' link is still TBD. There is some concern that if a page has 4-6 active maps on it that are all visible onload that the page will slow to a crawl.

**Comment by ldford** [comment]
Prioritizing the styling for compass maps appearing via iframe. Nick needs to be able to test how his maps look within OCS to make the final adjustments to the URLs that we will insert into WordPress. (See map at bottom of this page: http://ocs.ecotrust.org/strategy-habitat/aspen-woodlands/) 

Also: GIS team believes the maps served from Compass should NOT be displayed inline, but via a Show link/map icon.

**Comment by selenastrain** [comment]
@ldford are there design files for the Compass map styling? Also some of the maps are inline and some are supposed to be shown via the Map icon. Does GIS want all of the maps to be hidden by default?

**Comment by ldford** [comment]
@selenastrain The maps that are inline will be svg or png maps that Nick is creating. I think we should go ahead and show those. Content editors (like me) will be loading those into the WP Media Library and adding them into content via the "add media" button. They won't need styling. The maps that are coming from the Compass website via an iframe are the only ones to be hidden and then appear when someone clicks the map icon. Map icons might be in the middle of content or in a right-hand sidebar or in the top nav near the search bar where there are the grid/list/map view selections. Then the iframe takes over most of the screen as shown above.

@willthemoor what does Selena know re: styling in terms of the iframe?

**Comment by willthemoor** [comment]
The GIS team will take care of the actual map styling (everything within the iframe—map tiles, map controls...). The site just needs to display the iframe.  

The comps only have a "back" link in the top left to close the iframe when it's full screen. I imagine a lot of users are going to get stuck with that. Selena, can you also add a big X in the top right that also closes it since most users will be more familiar with that convention?  If possible, a little bit of small-to-big animation as it opens so users know something popped up vs having navigated to a new page would help as well.

**Comment by ldford** [comment]
Looping back on this with a good example of a Compass map that will be used on OCS. (See link below)

This map will show up in the iframe once a user clicks a "Map" icon. Our GIS team have devised it so that the state of Oregon will be centered within the iframe. At the bottom of the iframe will be the Legend tab; map sources line; and right above the sources will be the scale (they are moving that from the right side to the left).

The iframe will take up that whole area under the search nav bar and to the right of the lefthand nav bar. @selenastrain - you are responsible for the breadcrumbs (e.g. Conversation Actions / Back in the comp below) and the X (not currently in comps, but we need to have it at top-right corner) and the "View Data Layers in Compass" box at bottom right corner. The iframe will be underneath all that, and as you can see from the Compass map (link below) our GIS team left enough room for those 3 items to show up without covering anything important. (@willthemoor That's what the GIS team is expecting. Are we all on the same page?)

We want to be able to test our maps within the iframes as soon as possible. As we are waiting on a Map icon from the designers, can we use a placeholder? Right now, the only Compass map loaded into Wordpress to begin testing is the one here: http://ocs.ecotrust.org/strategy-habitat/aspen-woodlands/ 

Ideally on that page, "Aspen Woodlands" would be the page title, and therefore in the search bar. Then we would have a photo. Underneath the photo is the line "Aspen Woodlands Distribution" with a map icon. Clicking that icon would open the iframe with the Compass link that is already loaded into the back end.

Example of stylized compass map coming over via iframe:
http://52.25.124.64/visualize/#x=-121.58&y=43.76&z=7&logo=true&dls%5B%5D=true&dls%5B%5D=0.5&dls%5B%5D=472&basemap=ESRI+Satellite&themes%5Bids%5D%5B%5D=31&tab=data&print=true

Comp with iframe displayed:
![image](https://cloud.githubusercontent.com/assets/6453589/10440994/ebbbde60-70f8-11e5-8cc5-5631716a7ff7.png)

**Comment by dnseminara** [comment]
![screen shot 2015-11-06 at 2 19 59 pm](https://cloud.githubusercontent.com/assets/6739893/11010147/8b69d54c-8491-11e5-9dd8-653adf58f08f.png)

@ldford, here's what I'm going with at the moment. Are the breadcrumbs for single-species/habitats supposed to navigate back to their parent or just back to the original post? For example, in the above png - we're on the Aspen Woodlands view and it currently navigates back up to Strategy Habitats. Let me know if that's not correct.

Also, in the examples for earlier this month - they show more of a white background within the iframe. Within my png, the iframe and default esri basemap have labelling that could potentially clash with the visibility of the breadcrumb navigation. Are the iframes supposed to come with the white background and if not, should we be wrapping that navigation in the box - like the VIEW DATA LAYERS at the bottom?

**Comment by willthemoor** [comment]
I'm torn between the white frame and the super beauty @dnseminara has uploaded. 

Drew, I'm not sure what you mean about the white background within the iframe. Can you share an example of the white frame clashing with the esri labeling? I had imagined the older comp being more like a white box with an inner iframe so the breadcrumbs, close button and [View Data Layers in Compass] button would sit outside the iframe but within the white box.

One thought if we keep it full screen would be to put something behind the breadcrumbs. As it is, in this screenshot anyway, it looks like a another map label.  

I don't think the interaction with the breadcrumbs was specified. The X in the top right sould take you to Aspen Woodlands. Might be cool to have the breadcrumbs work like actual breadcrumbs where "back" would take you Aspen Woodlands and "Strategy Habitats" would take you the parent page. Usability would probably be greatly helped were it labeled as:

`Strategy Habitats / Back to Aspen Woodlands`

Either way, we need to ensure that the bottom fixed footer (the one about DRAFT) doesn't cover up the map attribution.

**Comment by ArtDezign** [comment]
Hey Will,

I’m still being included on these emails.  Could you have my email removed.

Thanks,

Lang

**Comment by dnseminara** [comment]
Hey, I got Mike to review my aforementioned comment with me. That current iframe that I grabbed from a previous example was missing certain params that solved the transparency issue. Sorry for the confusion! Here's what it *actually* looks like with the URL listed in the spreadsheet.

![screen shot 2015-11-06 at 3 06 43 pm](https://cloud.githubusercontent.com/assets/6739893/11010945/1b1b37a2-8498-11e5-9f54-b2042f3f9b4c.png)

Will, I was more worried about an issue where the labelling within the iframe would interact with the breadcrumb. For instance, esri labels (based on the zoom level) could potentially clash with the breadcrumb navigation. 

![screen shot 2015-11-06 at 3 16 58 pm](https://cloud.githubusercontent.com/assets/6739893/11011079/795d4dd6-8499-11e5-80cb-4a11d3d55807.png)

However, that wouldn't be the case if the navigations sat outside the iframe in a white box - as you mentioned or setting the iframe background completely to white. With the way the transparency is currently set for the URLs, it sounds like they may all need to be adjusted in the spreadsheet (so that they're completely white) to match an outer white box.

![screen shot 2015-11-06 at 3 28 05 pm](https://cloud.githubusercontent.com/assets/6739893/11011300/6e35edda-849b-11e5-8d52-f019c2bf1591.png)

Mike and I also discussed the breadcrumbs navigation and were wondering if they're a necessary component? We couldn't find any other mockup that shows them used outside of the iframe. The current functionality has an 'X' button on the top right  and the ability to toggle between the content when the user clicks the map icon (shown as the letter 'M'). I do like your suggestion of `Strategy Habitats` text going one place and `Back` working like the 'X'. Wondering if the user would notice the two?

**Comment by willthemoor** [comment]
Yep, I think the breadcrumbs could just go away. We do not use them elsewhere on the site (though perhaps we should). And yep yep, we added the X later due to concerns that people wouldn't even notice the breadcrumbs.

Again, I could go either way on the white frame. It's main benefit is helping the breadcrumb, X-close and View Data Layers button stand out and ensuring the legend and attribution remain on screen at all times. But most of that could just as easily be accomplished with some CSS on the elements themselves—white background on the breadcrumbs, drop shadow on the Compass button... maybe a white square behind the X that sorta screams *"I'm a button!"* for novice internet users. I'd rather explore that stuff because to my eyes the full screen map looks great.

**Comment by ldford** [comment]
I like the full-screen map as well versus the white background. And also, I want to X to scream a bit more. I think we're backwards when it comes to breadcrumbs - I don't think they are necessary on the maps, but I think they might help a whole lot for the rest of the site!

Drew: missing from this map are the scale, sources and legend tab that Ryan has built in to all Compass-OCS maps. Are those yet to come? If we decide to go in the direction of the full-screen map, I'd like to see where those go/how those look.

**Comment by dnseminara** [comment]
I'll add some styling to the 'X' and maybe slightly increase its size.  The color I took straight from the sidebar - should it perhaps be brighter?

The legend, scale, etc are there - they're just below the current window view, as I've been fighting with the map container UI and its relation to variable window sizes, as well as the sidebar. @willthemoor I may need some help on that, kind of been sloggin' on that for a while.

@rhodges - any way we can move Compass' attribute info? I talked to Mike about this. If one clicks - the attribute, the 'X' is in the same spot. Normally, I'd move the 'X' to save you time, but I feel like from a UX perspective, the close-button should *almost* always be in the upper right (except for those weird Apple/Mac folks). 

![screen shot 2015-11-09 at 2 34 06 pm](https://cloud.githubusercontent.com/assets/6739893/11048849/05042074-86ef-11e5-9704-e45bf5aa1ad2.png)

**Comment by ldford** [comment]
Drew: here is an example link of a COMPASS-OCS map. The scale, legend, and attributes are all in the bottom left-hand corner and bottom center. Ryan did this so that we would have the real estate we need for breadcrumbs (if we use them), X, and "view in Compass" link. 
http://52.25.124.64/visualize/#x=-121.58&y=43.76&z=7&logo=true&dls%5B%5D=true&dls%5B%5D=0.5&dls%5B%5D=472&basemap=ESRI+Satellite&themes%5Bids%5D%5B%5D=31&tab=data&print=true

**Comment by ldford** [comment]
See also: aspen woodlands map on the OCS dev site (bottom of page): http://ocs.ecotrust.org/strategy-habitat/aspen-woodlands/
That is how the Compass maps will be displayed in OCS.

**Comment by rhodges** [comment]
@ldford : @dnseminara is right about the 'identify' box being in the way of the 'top-right' close box.

I just created a ticket to drop it down when viewing on OCS : https://github.com/Ecotrust/COMPASS/issues/67

**Comment by dnseminara** [comment]
Yup! But if you click on a specific point in the Aspen-Woodland map in the link above, you'll see that the attributes for that particular spot also appear in the upper right hand corner. Currently, since the map is now fullscreen, it'll interfere with where I placed the 'X'. In the below example, I changed the color of the 'X' so it's more visible for this demo.

![screen shot 2015-11-09 at 3 09 27 pm](https://cloud.githubusercontent.com/assets/6739893/11049553/f5903b28-86f3-11e5-88be-2be7cdb7f869.png)

**Comment by ldford** [comment]
got it. Looks like Ryan has it covered.

**Comment by ldford** [comment]
p.s. thanks for all the screenshots

**Comment by ldford** [comment]
@willthemoor @dnseminara I forget who this should be assigned to. Will changed the pixel height of our footer and now our legend and map attribution have fallen off the bottom of the page again - hiding under our footer:

![image](https://cloud.githubusercontent.com/assets/6453589/11701008/f1ff0386-9e81-11e5-9828-ac07373c6f8f.png)

**Comment by dnseminara** [comment]
@ldford It's mine, I can change it. Is that footer *always* going to be there, perhaps I should actually use logic rather than styling to set the view of compass map.
