### ISSUE TITLE
Sidebar Navigation - ONS

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#37]
Need to handle Nearshore slightly differently than the other pages because they're nested so deeply. Laura, assigning this to you first so that we can get a meeting together to figure out the best approach to implement.

Related to #17 and #34.

**Comment by ldford** [comment]
Thought I left comment here yesterday but must have never pushed the button. Greg and I cleaned up/fixed all ONS sidebar nav. Only ONE ONS sidebar heading now has nested subheads (habitats). We decreased the number of headers by combining many.

I want something in the sidebar dropdown (versus flyout) to indicate that the habitat subheads are actually UNDER habitats - not on the same level. So I did this - which seems like it's all it really needs. But if you have a better idea @willthemoor, go for it. Otherwise, let's close this.

![image](https://cloud.githubusercontent.com/assets/6453589/12206533/5d49f0fc-b5f6-11e5-91a3-1e6135227f64.png)
