### ISSUE TITLE
Ecoregion Grid Images Throwing Error - Live but not Local

### ISSUE THREAD

**Issue by dnseminara** [Ecotrust/ocs-wp#48]
"Trying to get property of non object - line 35 in cpt-ecoregions.php"

**Comment by willthemoor** [comment]
It's a little counter intuitive and a product of legacy-naming but in WordPress the global object `$post` means "the current thing being viewed/worked on". It's sort of like `ActiveRecord` in Rails. So, even though the error is coming up on a `page` and we're looping through `ecoregion` custom post types where the error is triggered, you still use `$post->ID` to get the ID of the current object. Because, WordPress.

```php
<div class="image-grid-container">
	<?php if ( has_post_thumbnail($post->ID) ) : ?>
		<?php echo get_the_post_thumbnail($post->ID, 'large', array('class' => 'img-responsive')) ?>
	<?php endif; ?>
</div>
```

Unrelated but might as well put the `has_post_thumbnail()` check outside of `<div class="image-grid-container">`
