### ISSUE TITLE
Add species URLs to WP

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#75]
Reimport CSV and include the larger image size as the post_thumbnail.

**Comment by ldford** [comment]
I have a question for you @willthemoor about broken species images because the URLs are bad. They aren't importing as photos because, well, the URL is bad. But I can fix the URL. Can I do this in the CSV before you reimport? And, I noticed that when importing, the attribution is not coming through for the photo in the media library. The attribution is still being pulled from the CSV import. Which is fine, unless the photo is uploaded from the media library to use somewhere else on the site. It won't have attribution info connected to it.

**Comment by willthemoor** [comment]
Yes, you can fix the URLs before I import again but let me send you the newest version of the sheet. 

And good catch on the attribution. We'll need to move that to the image instead of the species post.

**Comment by ldford** [comment]
Send me the spreadsheet, and I will fix!

**Comment by ldford** [comment]
@willthemoor remember to send me the newest version of the strategy species spreadsheet. thanks.

**Comment by willthemoor** [comment]
Note, when importing species photos that some of the current versions are in use in the ONS. For instance, http://ocs.ecotrust.org/nearshore-invertebrates-test-page/ 

If they need to be removed, be sure to replace any references to them with the new URLs.

**Comment by ldford** [comment]
@willthemoor I'm completely done with the strategy species spreadsheet. I won't touch it again. Import whenever you are ready. Remember to move photo attribution info to the photo (from the species post).

**Comment by ldford** [comment]
Will - Greg asking me about this again. Can you let me know when you think you'll be able to import the updated spreadsheet? Thanks.

**Comment by willthemoor** [comment]
This is live.
